### ISSUE TITLE
Azure CDNの検証と設置

### ISSUE THREAD

**Issue by reone19** [hal-tokyo-cello/actions-test-front#1]
Azure CDNの作成について
①CDNのプロファイルの追加(江畑先生に作ってもらう必要がありそう)
②エンドポイントの追加
参考URL↓
https://docs.microsoft.com/ja-jp/azure/cdn/cdn-create-new-endpoint 

![Image](https://user-images.githubusercontent.com/66284670/174720627-d04a2b6a-afb7-437e-89eb-e95f1fea0c1e.png)

**Comment by updandan** [comment]
・権限問題
江畑先生に頼んで解決。

・追加の問題
エンドポイントのURLにアクセスすると500err吐く。
(blob側ならアクセス可)
